"""
Base strategy interface.
All strategies must implement this interface to plug into the engine.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    stock: str
    action: str           # "BUY" or "SELL"
    entry_price: float
    stop_loss: float
    target_price: float
    quantity: int          # Suggested quantity (risk manager may override)
    strategy: str          # Name of strategy that generated this
    confidence: float      # 0.0 to 1.0
    reason: str            # Human-readable reason for the signal
    timestamp: str = ""


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    @abstractmethod
    def name(self) -> str:
        """Strategy name for logging and identification."""
        pass

    @abstractmethod
    def scan(self, watchlist: list[str]) -> list[Signal]:
        """
        Scan the watchlist and return any actionable signals.
        Called once per scan cycle (typically once per day for swing trading).
        """
        pass

    @abstractmethod
    def should_exit(self, stock: str, current_price: float, entry_price: float) -> Optional[Signal]:
        """
        Check if an open position should be exited.
        Returns an exit Signal if yes, None if hold.
        """
        pass
